import type { WebBook } from "@/types/web-book"

export const mockWebBooks: WebBook[] = [
  {
    id: "book-1",
    title: "The Complete Guide to Content Marketing",
    description: "Learn everything you need to know about content marketing strategies, SEO, and audience engagement.",
    coverImage: "/content-marketing-guide.png",
    author: {
      id: "user-1",
      name: "Alex Johnson",
      avatar: "/abstract-profile.png",
    },
    chapterCount: 12,
    createdAt: "2023-11-15T10:30:00Z",
    updatedAt: "2023-12-01T14:45:00Z",
    isPublished: true,
    visibility: "public",
  },
  {
    id: "book-2",
    title: "Social Media Strategy 2023",
    description: "A comprehensive guide to building and executing effective social media strategies across platforms.",
    coverImage: "/social-media-strategy.png",
    author: {
      id: "user-1",
      name: "Alex Johnson",
      avatar: "/abstract-profile.png",
    },
    chapterCount: 8,
    createdAt: "2023-10-05T08:20:00Z",
    updatedAt: "2023-11-20T11:15:00Z",
    isPublished: true,
    visibility: "public",
  },
  {
    id: "book-3",
    title: "Email Marketing Mastery",
    description:
      "Master the art of email marketing with proven templates, automation strategies, and conversion tactics.",
    coverImage: "/email-marketing-concept.png",
    author: {
      id: "user-1",
      name: "Alex Johnson",
      avatar: "/abstract-profile.png",
    },
    chapterCount: 6,
    createdAt: "2023-09-12T15:40:00Z",
    updatedAt: "2023-10-25T09:30:00Z",
    isPublished: false,
    visibility: "private",
  },
  {
    id: "book-4",
    title: "Video Production Essentials",
    description: "Everything you need to know about creating professional videos for marketing and social media.",
    coverImage: "/video-production-team.png",
    author: {
      id: "user-1",
      name: "Alex Johnson",
      avatar: "/abstract-profile.png",
    },
    chapterCount: 10,
    createdAt: "2023-08-20T12:10:00Z",
    updatedAt: "2023-09-18T16:25:00Z",
    isPublished: true,
    visibility: "public",
  },
  {
    id: "book-5",
    title: "Brand Identity Guidelines",
    description: "Internal guidelines for maintaining consistent brand identity across all marketing materials.",
    coverImage: null,
    author: {
      id: "user-1",
      name: "Alex Johnson",
      avatar: "/abstract-profile.png",
    },
    chapterCount: 5,
    createdAt: "2023-07-08T09:15:00Z",
    updatedAt: "2023-08-05T13:40:00Z",
    isPublished: true,
    visibility: "private",
  },
  {
    id: "book-6",
    title: "SEO Best Practices 2023",
    description: "The latest SEO techniques and strategies to improve your website's search engine rankings.",
    coverImage: "/seo-best-practices.png",
    author: {
      id: "user-1",
      name: "Alex Johnson",
      avatar: "/abstract-profile.png",
    },
    chapterCount: 9,
    createdAt: "2023-06-15T11:20:00Z",
    updatedAt: "2023-07-22T10:05:00Z",
    isPublished: false,
    visibility: "private",
  },
]
