export const forumTopics = [
  {
    id: 1,
    title: "Best practices for AI-generated blog content",
    excerpt: "What are your tips for getting the most out of the AI blog generator?",
    author: "AlexCreator",
    replies: 24,
    lastReply: "2 hours ago",
    isHot: true,
  },
  {
    id: 2,
    title: "How to effectively use version history",
    excerpt: "I'm trying to understand the best workflow for tracking changes...",
    author: "ContentPro",
    replies: 8,
    lastReply: "yesterday",
    isHot: false,
  },
  {
    id: 3,
    title: "Integration with Webflow - step by step guide",
    excerpt: "I've set up a seamless workflow between CreaVibe and Webflow...",
    author: "WebflowWizard",
    replies: 15,
    lastReply: "3 days ago",
    isHot: false,
  },
  {
    id: 4,
    title: "Team collaboration best practices",
    excerpt: "Our marketing team has been using CreaVibe for 3 months now...",
    author: "TeamLeadSarah",
    replies: 12,
    lastReply: "1 week ago",
    isHot: false,
  },
  {
    id: 5,
    title: "Image generation tips and tricks",
    excerpt: "I've discovered some amazing prompts for the image generator...",
    author: "VisualCreator",
    replies: 31,
    lastReply: "5 hours ago",
    isHot: true,
  },
]

export const upcomingWebinars = [
  {
    id: 1,
    title: "Getting Started with CreaVibe",
    description: "Learn the basics and set up your first project in this beginner-friendly session.",
    date: "May 25, 2023",
    time: "11:00 AM - 12:00 PM PT",
    isFree: true,
  },
  {
    id: 2,
    title: "Advanced AI Content Generation",
    description: "Master the art of crafting perfect prompts for exceptional AI-generated content.",
    date: "May 28, 2023",
    time: "1:00 PM - 2:30 PM PT",
    isFree: false,
  },
  {
    id: 3,
    title: "Collaborative Workflows for Marketing Teams",
    description: "Optimize your team's content creation process with real-time collaboration.",
    date: "June 2, 2023",
    time: "10:00 AM - 11:00 AM PT",
    isFree: true,
  },
  {
    id: 4,
    title: "Integrating CreaVibe with Your Tech Stack",
    description: "Connect CreaVibe with your existing tools for a seamless workflow.",
    date: "June 8, 2023",
    time: "2:00 PM - 3:00 PM PT",
    isFree: false,
  },
]

export const featureRequests = [
  {
    id: 1,
    title: "PDF to Blog Post Converter",
    description: "Add the ability to upload a PDF and convert it into a well-formatted blog post.",
    votes: 342,
    status: "Under consideration",
    progress: 25,
  },
  {
    id: 2,
    title: "Advanced SEO Recommendations",
    description: "Provide SEO suggestions and keyword optimization as content is being created.",
    votes: 528,
    status: "Planned",
    progress: 50,
  },
  {
    id: 3,
    title: "Video Content Generation",
    description: "Expand AI capabilities to include video script and storyboard generation.",
    votes: 476,
    status: "In development",
    progress: 75,
  },
  {
    id: 4,
    title: "Custom Brand Voice Training",
    description: "Allow users to train the AI on their brand's unique voice and style.",
    votes: 389,
    status: "Planned",
    progress: 40,
  },
  {
    id: 5,
    title: "Slack Integration",
    description: "Receive notifications and collaborate on content directly from Slack.",
    votes: 267,
    status: "Under consideration",
    progress: 15,
  },
  {
    id: 6,
    title: "Content Calendar & Scheduling",
    description: "Plan, schedule, and automate content publishing across multiple platforms.",
    votes: 612,
    status: "In development",
    progress: 85,
  },
]
